### ISSUE TITLE
Suggestion) Why don't we make fibo.py

### ISSUE THREAD

**Issue by sjhh4** [sjhh4/branch-practice#1]
Fibonacci Sequence를 구하는 파이썬 스크립트를 짜는건 어떤가요??

## Tasks

- [ ] Fibo with Recursion
- [ ] Fibo with Memorization
- [ ] Fibo with binet's formula

$$F_n=\dfrac{\left(\dfrac{1+\sqrt{5}}{2}\right)^n-\left(\dfrac{1-\sqrt{5}}{2}\right)^n}{\sqrt{5}}$$
